<?php
$t = $this->plugin('translate');
$urlHelper = $this->plugin('url');
$escapeAttr = $this->plugin('escapeHtmlAttr');
?>
<ul>
    <li>
        <?php $url = $urlHelper('site/guest-user', ['action' => 'update-account'], [], true); ?>
        <a href="<?php echo $escapeAttr($url); ?>"><?php echo $t('Update account info and password'); ?></a>
    </li>
    <li>
        <?php $url = $urlHelper('site/guest-user', ['action' => 'update-email'], [], true); ?>
        <a href="<?php echo $escapeAttr($url); ?>"><?php echo $t('Update email'); ?></a>
    </li>
</ul>
