<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Entity\User $user
 * @var array $links
 */

// Make compatible with old themes that call partial directly.
if (!array_key_exists('user', get_defined_vars())): echo $this->userBar(); return; endif;

$translate = $this->plugin('translate');
$hyperlink = $this->plugin('hyperlink');
$urlHelper = $this->plugin('url');
$this->headLink()
    ->prependStylesheet($this->assetUrl('css/user-bar.css', 'Omeka'))
    ->prependStylesheet('//fonts.googleapis.com/css?family=Source+Code+Pro|Lato:400,400italic,700,700italic');

$adminRights = $user && $this->userIsAllowed('Omeka\Controller\Admin\Index', 'index');
?>
<style>
#user-bar .admin:not(:last-child):not(:nth-last-child(2)):not(:nth-last-child(3)):after {
    content: "\2022";
    margin: 0 12px;
}
#user-bar .user-id {
    margin-left: auto;
}
</style>
<div id="user-bar">
<?php if ($user): ?>
    <?php foreach ($links as $link): ?>
    <span class="admin <?php echo $link['resource'] . ' ' . $link['action']; ?>">
        <?php echo $hyperlink($link['text'], $link['url']); ?>
    </span>
    <?php endforeach; ?>

    <span class="user-id">
        <?php
        $url = $adminRights
            ? $urlHelper('admin/id', ['controller' => 'user', 'id' => $user->getId()])
            : $urlHelper('site/guest-user', ['site-slug' => $site->slug(), 'action' => 'me', 'id' => $user->getId()]);
        echo sprintf($translate('Signed in as %s'), $hyperlink($user->getName(), $url));
        ?>
    </span>
    <span class="logout">
        <?php
        $url = $urlHelper('site/guest-user', ['site-slug' => $site->slug(), 'action' => 'logout'], ['query' => $this->params()->fromQuery() ?: []], true);
        echo $hyperlink($translate('Logout'), $url, ['class' => 'logout']);
        ?>
    </span>
<?php else: ?>
    <span class="login">
        <?php
        $url = $urlHelper('site/guest-user', ['site-slug' => $site->slug(), 'action' => 'login'], ['query' => $this->params()->fromQuery() ?: []], true);
        echo $hyperlink($translate('Log in'), $url, ['class' => 'login']);
        ?>
    </span>
<?php endif; ?>
</div>
