<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Entity\User $user
 * @var array $links
 */

$translate = $this->plugin('translate');
$hyperlink = $this->plugin('hyperlink');
$urlHelper = $this->plugin('url');
$this->headLink()
    ->prependStylesheet($this->assetUrl('css/user-bar.css', 'Omeka'))
    ->prependStylesheet('//fonts.googleapis.com/css?family=Source+Code+Pro|Lato:400,400italic,700,700italic');

$adminRights = isset($user) && $this->userIsAllowed('Omeka\Controller\Admin\Index', 'index');
?>
<div id="user-bar">
<?php if (isset($user)): ?>
    <div class="site-links">
    <?php foreach ($links as $link): ?>
        <span class="admin <?php echo $link['resource'] . ' ' . $link['action']; ?>">
            <?php echo $hyperlink($link['text'], $link['url']); ?>
        </span>
    <?php endforeach; ?>
    </div>

    <div class="user-links">
        <span class="user-id">
            <?php
            $url = $adminRights
                ? $urlHelper('admin/id', ['controller' => 'user', 'id' => $user->getId()])
                : $urlHelper('site/guest-user', ['site-slug' => $site->slug(), 'action' => 'me', 'id' => $user->getId()]);
            echo sprintf($translate('Signed in as %s'), $hyperlink($user->getName(), $url));
            ?>
        </span>
        <?php
        $url = $urlHelper('site/guest-user', ['site-slug' => $site->slug(), 'action' => 'logout'], ['query' => $this->params()->fromQuery() ?: []], true);
        echo $hyperlink($translate('Logout'), $url, ['class' => 'logout']);
        ?>
    </div>
<?php else: ?>
    <span class="login">
        <?php
        $url = $urlHelper('site/guest-user', ['site-slug' => $site->slug(), 'action' => 'login'], ['query' => $this->params()->fromQuery() ?: []], true);
        echo $hyperlink($translate('Log in'), $url, ['class' => 'login']);
        ?>
    </span>
<?php endif; ?>
</div>
