<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Form\ForgotPasswordForm $form
 */

$translate = $this->plugin('translate');

$this->htmlElement('body')->appendAttribute('class', 'guest-user forgot-password');
$form->prepare();
?>

<h1><?= $translate('Forgot Password') ?></h1>
<?= $this->messages() ?>
<?= $this->form()->openTag($form) ?>
<?= $this->formCollection($form, false) ?>
<button><?= $translate('Send an email to reset the password') ?></button>
<?= $this->form()->closeTag() ?>
