<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \GuestUser\Form\UserForm $form
 * @var string $registerLabel
 */

$translate = $this->plugin('translate');

$this->htmlElement('body')->appendAttribute('class', 'guest-user register');
$form->prepare();
?>

<?= $this->messages() ?>

<?= $this->pageTitle($translate('Register')) ?>
<label><?= $registerLabel ?></label>

<?= $this->form()->openTag($form) ?>
<?= $this->formCollection($form, false) ?>
<?php $this->trigger('view.add.form.after'); ?>
<div id="page-actions">
    <button><?= $translate('Register') ?></button>
</div>
<?= $this->form()->closeTag() ?>

<?php $this->trigger('view.add.after'); ?>
