<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Entity\User $user
 * @var \Omeka\Settings\UserSettings $userSettings
 * @var \Omeka\Api\Representation\SiteRepresentation|null $guestSite
 */

$translate = $this->plugin('translate');
?>

<div class="property guest-profile">
    <h4><?= $translate('Guest account') ?></h4>
    <div class="value guest-account">
        <ul class="guest-account">
            <li>
                <?= sprintf($translate('Site: %s'), $guestSite ? $guestSite->link($guestSite->title()) : $this->translate('none')) ?>
            </li>
        </ul>
    </div>
</div>
