<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \GuestUser\Form\AcceptTermsForm $form
 * @var string $text
 * @var string $page
 */

$translate = $this->plugin('translate');

$this->htmlElement('body')->appendAttribute('class', 'guest-user accept-terms');
$form->prepare();
?>

<?= $this->messages() ?>

<?= $this->pageTitle($translate('Accept terms and conditions')) ?>

<?= $text ?>

<?= $this->form()->openTag($form) ?>
<div id="page-actions">
    <button><?= $translate('Accept') ?></button>
</div>

<?= $this->formCollection($form, false) ?>
<?php $this->trigger('view.add.form.after'); ?>
<?= $this->form()->closeTag() ?>

<?php if ($page): ?>
<?= sprintf($translate('The terms and conditions can be read %shere%s.'),
    '<a href="' . $this->url('site/page', ['page-slug' => $page], [], true) . '">', '</a>') ?>
<?php endif; ?>

<?php $this->trigger('view.add.after'); ?>
