<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var array $widgets
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$setting = $plugins->get('setting');
$pageTitle = $plugins->get('pageTitle');

$guestUserWidget = $plugins->get('guestUserWidget');

$this->htmlElement('body')->appendAttribute('class', 'guest-user account');
?>

<?= $pageTitle($translate($setting('guestuser_dashboard_label'))) ?>

<?= $this->messages() ?>

<?php foreach ($widgets as $widget): ?>
<div class="guest-user-widget">
    <?= $guestUserWidget($widget) ?>
</div>
<?php endforeach; ?>
