<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \GuestUser\Form\EmailForm $form
 */

$translate = $this->plugin('translate');

$this->htmlElement('body')->appendAttribute('class', 'guest-user account');
$form->prepare();
?>

<?= $this->messages() ?>

<?= $this->pageTitle($translate('My email')) ?>

<?= $this->form()->openTag($form) ?>
<?= $this->formCollection($form, false) ?>
<?php $this->trigger('view.add.form.after'); ?>
<div id="page-actions">
    <button><?= $translate('Update') ?></button>
</div>
<?= $this->form()->closeTag() ?>

<?php $this->trigger('view.add.after'); ?>
