<?php
$this->htmlElement('body')->appendAttribute('class', 'guest-user account');
$form->prepare();
?>

<?php echo $this->messages(); ?>

<?php echo $this->pageTitle($this->translate('My email')); ?>

<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <button><?php echo $this->translate('Update'); ?></button>
</div>

<?php echo $this->formCollection($form, false); ?>
<?php $this->trigger('view.add.form.after'); ?>
<?php echo $this->form()->closeTag(); ?>

<?php $this->trigger('view.add.after'); ?>
