<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Form\LoginForm $form
 */

$translate = $this->plugin('translate');

$this->htmlElement('body')->appendAttribute('class', 'guest login');
?>

<?= $this->pageTitle($this->siteSetting('guest_login_text') ?: ($this->setting('guest_login_text') ?: $translate('Login'))) ?>

<?= $this->messages() ?>

<?php if (empty($form)): ?>
<p>
    <?= $translate('Your account seems to have an error. Contact your administrator to login.') ?>
</p>
<?php else: ?>
<?= $this->form($form) ?>
<?php endif; ?>

<p class="forgot-password">
    <?= $this->hyperlink($translate('Forgot password?'), $this->url('site/guest/anonymous', ['action' => 'forgot-password'], true)) ?>
</p>

<?php $this->trigger('view.login.after'); ?>
