<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Form\UserForm $form
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$setting = $plugins->get('setting');
$siteSetting = $plugins->get('siteSetting');

$this->htmlElement('body')->appendAttribute('class', 'guest register');
$form->prepare();
?>

<?= $this->messages() ?>

<?= $this->pageTitle($siteSetting('guest_register_text') ?: ($setting('guest_register_text') ?: $translate('Register'))) ?>
<div><?= $siteSetting('guest_capabilities') ?: ($setting('guest_capabilities')) ?></div>

<?= $this->form()->openTag($form) ?>
<?= $this->formCollection($form, false) ?>
<?php $this->trigger('view.add.form.after'); ?>
<div id="page-actions">
    <button><?= $translate('Register') ?></button>
</div>
<?= $this->form()->closeTag() ?>

<?php $this->trigger('view.add.after'); ?>
