<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 */

$translate = $this->plugin('translate');
$hyperlink = $this->plugin('hyperlink');
$urlHelper = $this->plugin('url');
?>

<ul>
    <li>
        <?php $url = $urlHelper('site/guest-user', ['action' => 'update-account'], [], true); ?>
        <?= $hyperlink($translate('Update account info and password'), $url) ?>
    </li>
    <li>
        <?php $url = $urlHelper('site/guest-user', ['action' => 'update-email'], [], true); ?>
        <?= $hyperlink($translate('Update email'), $url) ?>
    </li>
    <li>
        <?php $url = $urlHelper('site/guest-user', ['action' => 'logout'], [], true); ?>
        <?= $hyperlink($translate('Logout'), $url) ?>
    </li>
</ul>
