<?php
//$pageTitle =  get_option('guest_user_dashboard_label');
// echo head(array('title' => $pageTitle));
?>
<h1><?php  ?></h1>


<?php foreach($this->widgets as $index=>$widget): ?>
<div class='guest-user-widget <?php if($index & 1): ?>guest-user-widget-odd <?php else:?>guest-user-widget-even<?php endif;?>'>
<?php echo \GuestUser\Module::guestUserWidget($widget); ?>
</div>
<?php endforeach; ?>
