<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Site\Navigation\Link\LinkInterface $link
 * @var array $data
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$data = is_array($data) ? $data : [];
$data = array_map('trim', $data) + [
    'label-login' => '',
    'label-board' => '',
];
?>

<label><?= $translate('Type') ?> <input type="text" value="<?= $escape($translate($link->getName())) ?>" disabled="disabled"></label>
<label><?= $translate('Label Login') ?> <input type="text" data-name="label-login" value="<?= $escape($data['label-login']) ?>"></label>
<label><?= $translate('Label My board') ?> <input type="text" data-name="label-board" value="<?= $escape($data['label-board']) ?>"></label>
