<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Site\Navigation\Link\LinkInterface $link
 * @var array $data
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$label = isset($data['label']) && '' !== trim($data['label']) ? $data['label'] : null;
?>

<label><?= $translate('Type') ?> <input type="text" value="<?= $escape($translate($link->getName())) ?>" disabled="disabled"></label>
<label><?= $translate('Label') ?> <input type="text" data-name="label" value="<?= $escape($label) ?>"></label>
